exports.LOGIN_TYPE = {
  GOOGLE: 1,
  QUICK: 2,
  MOBILE_NUMBER: 3,
  EMAIL_PASSWORD: 4,
  APPLE: 5,
};

exports.LISTENER_REQUEST_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};

exports.HISTORY_TYPE = {
  LOGIN_BONUS: 1,
  COIN_PLAN_PURCHASE: 2,
  PRIVATE_AUDIO_CALL: 3,
  PRIVATE_VIDEO_CALL: 4,
  RANDOM_AUDIO_CALL: 5,
  RANDOM_VIDEO_CALL: 6,
  WITHDRAWAL_BY_LISTENER: 7,
  ADMIN_ADD_COIN: 8,
  ADMIN_DEDUCT_COIN: 9,
  ADMIN_ADD_COIN_TO_LISTENER: 10,
  ADMIN_DEDUCT_COIN_FROM_LISTENER: 11,
};

exports.MESSAGE_TYPE = {
  MESSAGE: 1,
  IMAGE: 2,
  AUDIO: 3,
  AUDIO_CALL: 4,
  VIDEO_CALL: 5,
};

exports.CALL_TYPE = {
  RECEIVED: 1,
  DECLINED: 2,
  MISCALLED: 3,
};

exports.WITHDRAWAL_STATUS = {
  DEFAULT: 0,
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};

exports.STATUS_OF_REPORT = {
  PENDING: 1,
  SOLVED: 2,
};
