module.exports = {
  currency: {
    name: "Dollar",
    symbol: "$",
    countryCode: "US",
    currencyCode: "USD",
    isDefault: true
  },
  _id: "69d8d904e2238aa47056180f",
  privacyPolicyUrl: "PRIVACY POLICY LINK UPDATE",
  termsOfUseUrl: "TERMS OF USE POLICY LINK UPDATE",
  isGooglePlayEnabled: true,
  isStripeEnabled: true,
  stripePublicKey: "STRIPE_PUBLIC_KEY",
  stripeSecretKey: "STRIPE_SECRET_KEY",
  isRazorpayEnabled: true,
  razorpayKeyId: "RAZORPAY_KEY_ID",
  razorpayKeySecret: "RAZORPAY_KEY_SECRET",
  isFlutterwaveEnabled: true,
  flutterwavePublicKey: "FLUTTERWAVE_PUBLIC_KEY",
  agoraAppId: "AGORA APP ID UPDATE",
  agoraAppCertificate: "AGORA APP CERTIFICATE UPDATE",
  dailyLoginBonusCoins: 50,
  isDemoContentEnabled: true,
  isApplicationLive: true,
  allowBecomeHostOption: true,
  adminCommissionPercent: 20,
  minimumCoinsForConversion: 100,
  minimumCoinsForPayout: 10,
  videoCallRatePrivate: 2,
  audioCallRatePrivate: 1,
  videoCallRateRandom: 40,
  audioCallRateRandom: 20,
  privateKey: {},
  createdAt: "2025-05-12T11:11:45.825Z",
  updatedAt: "2026-07-03T09:13:36.053Z",
  zegoAppId: "zegoAppId",
  zegoAppSignIn: "zegoAppSignIn",
  aboutUsUrl: "https://married-copper-vebibx6pkp.edgeone.dev/",
  listenerPrivacyPolicyUrl: "https://www.termsfeed.com/live/cd67f429-2d47-426a-a018-59c32a82e0fd",
  userPrivacyPolicyUrl: "https://www.termsfeed.com/live/cd67f429-2d47-426a-a018-59c32a82e0fd",
  helpdeskEmail: "helpdeskEmail",
  cashfreeClientId: "CASHFREE_CLIENT_ID",
  cashfreeClientSecret: "CASHFREE_CLIENT_SECRET",
  isCashfreeAndroidEnabled: true,
  isCashfreeIosEnabled: true,
  isFlutterwaveIosEnabled: true,
  isGooglePlayIosEnabled: true,
  isPaypalAndroidEnabled: true,
  isPaypalIosEnabled: true,
  isPaystackAndroidEnabled: true,
  isPaystackIosEnabled: true,
  isRazorpayIosEnabled: true,
  isStripeIosEnabled: true,
  paypalClientId: "PAYPAL_CLIENT_ID",
  paypalSecretKey: "PAYPAL_SECRET_KEY",
  paystackPublicKey: "PAYSTACK_PUBLIC_KEY",
  paystackSecretKey: "PAYSTACK_SECRET_KEY",
  androidAppLink: "https://andriodapplink.com",
  androidAppVersion: "1.0.0",
  iosAppLink: "https://iosapplink.com",
  iosAppVersion: "1.0.0"
};
